# Generated by Django 2.2.5 on 2019-10-11 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191010_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Especie')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cor', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=5)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raca')),
            ],
        ),
    ]
