# Generated by Django 2.2.5 on 2019-10-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_animal_especie_raca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='contato',
        ),
        migrations.AlterField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=5),
        ),
    ]
