# Generated by Django 2.2.5 on 2019-10-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191022_2015'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservicoexterna',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Servico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservicointerna',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Servico'),
            preserve_default=False,
        ),
    ]
