# Generated by Django 2.2.5 on 2019-10-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191022_2015'),
        ('frente_de_caixa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendas',
            new_name='Venda',
        ),
    ]
