# Generated by Django 2.2.5 on 2019-10-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frente_de_caixa', '0002_auto_20191022_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
