# Generated by Django 2.2.5 on 2019-10-22 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frente_de_caixa', '0003_auto_20191022_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensdevenda',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Produto'),
        ),
        migrations.AlterField(
            model_name='itensdevenda',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Servico'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
