# Generated by Django 2.2.5 on 2019-10-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro_estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
